#default configuration file for pifan
[fan]
    temp_low = 45.0
    temp_high = 75.0
    controller = "max_speed"
    gpio_pin = "GPIO12"
    frequency = 100 # control pulse frequency in Hz

[daemon]
    update_interval = 5 # amount of time in seconds to sleep between checking temperature
